language: csharp
dist: trusty
mono: none
dotnet: 2.1
install:
- dotnet restore
script:
- dotnet build derbytracker.common.tests/derbytracker.common.tests.csproj
- dotnet test DerbyTracker.Common.Tests/DerbyTracker.Common.Tests.csproj